### ISSUE TITLE
[Deployment] use Netlify for deployment

### ISSUE THREAD

**Issue by siddhantprateek** [NikhitaBarat/portfolio#1]
Create `netlify.toml` file at your root repository.
 
add 
```
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

Deploy it to Netlify

https://aviyel.com/post/2891/how-to-deploy-docz-in-netlify

follow it from **Deploying your Website to Netlify**
@NikhitaBarat

**Comment by NikhitaBarat** [comment]
done
